using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace UniversityWPF.Model;

public class UniversityContext : DbContext
{
	public DbSet<Course> Courses { get; set; } = null!;
	public DbSet<Group> Groups { get; set; } = null!;
	public DbSet<Student> Students { get; set; } = null!;

	public UniversityContext(DbContextOptions<UniversityContext> options)
		: base(options)
	{
	}

	//protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	//{
	//	optionsBuilder.UseSqlServer("Server=localhost;Database=University;Trusted_Connection=True;Encrypt=False;");
	//}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Course>(entity =>
		{
			entity.HasKey(c => c.CourseId).HasName("PK_Courses_CourseId");
			entity.HasIndex(c => c.Name, "UQ_Courses_Name").IsUnique();
			entity.Property(c => c.Name).HasMaxLength(50);
		});

		modelBuilder.Entity<Group>(entity =>
		{
			entity.HasKey(g => g.GroupId).HasName("PK_Groups_GroupId");
			entity.HasIndex(g => g.Name, "UQ_Groups_Name").IsUnique();
			entity.Property(g => g.Name).HasMaxLength(50);
			entity.HasOne(g => g.Course).WithMany(c => c.Groups)
				.HasForeignKey(g => g.CourseId)
				.OnDelete(DeleteBehavior.Restrict)
				.HasConstraintName("FK_Groups_Courses");
		});

		modelBuilder.Entity<Student>(entity =>
		{
			entity.HasKey(s => s.StudentId).HasName("PK_Students_StudentId");
			entity.Property(s => s.FirstName).HasMaxLength(50);
			entity.Property(s => s.LastName).HasMaxLength(50);
			entity.HasOne(s => s.Group).WithMany(g => g.Students)
				.HasForeignKey(s => s.GroupId)
				.OnDelete(DeleteBehavior.Restrict)
				.HasConstraintName("FK_Students_Groups");
		});

		modelBuilder.Entity<Course>().HasData(
			new Course { CourseId = 1, Name = "Geography", Description = "Bachelor in Geography programs are structured to provide specialized training in many geography centric areas" },
			new Course { CourseId = 2, Name = "Geology", Description = "Bachelor of Geology is a program that focuses on the study of the solid earth and it’s processes of evolution" },
			new Course { CourseId = 3, Name = "Hydrometeorology", Description = "The bachelor’s programme ‘Hydrometeorology’ makes it possible for students to master both general basic courses in geography and hydrometeorology, and obtain knowledge in a particular area" },
			new Course { CourseId = 4, Name = "Real Estate Management", Description = "Pursuit of a bachelor’s degree provides the opportunity for advanced instruction at the university level with emphasis in a selected field" },
			new Course { CourseId = 5, Name = "Cartography", Description = "A bachelor’s degree is an undergraduate degree that is offered by universities and colleges when students complete a program of study" },
			new Course { CourseId = 6, Name = "Oil and Gas", Description = "A bachelor’s degree is widely considered to be the first degree in a series of possible higher education pursuits" },
			new Course { CourseId = 7, Name = "Tourism", Description = "The Bachelor of Tourism degree will provide students with the fundamental knowledge of the tourism industry, preparing for exciting jobs in the field of tourism" },
			new Course { CourseId = 8, Name = "Soil science", Description = "A bachelor’s degree is awarded to individuals who have completed their undergraduate studies in a chosen field" },
			new Course { CourseId = 9, Name = "Ecology and nature management", Description = "The field of ecology involves the study of living organisms, their interactions with each other, as well as the environment" }
			);

		modelBuilder.Entity<Group>().HasData(
			new Group { GroupId = 1, CourseId = 1, Name = "SD-09" },
			new Group { GroupId = 2, CourseId = 2, Name = "SH-23" },
			new Group { GroupId = 3, CourseId = 1, Name = "SX-22" },
			new Group { GroupId = 4, CourseId = 5, Name = "SA-33" },
			new Group { GroupId = 5, CourseId = 6, Name = "SG-11" },
			new Group { GroupId = 6, CourseId = 1, Name = "SR-01" },
			new Group { GroupId = 7, CourseId = 8, Name = "SC-06" },
			new Group { GroupId = 8, CourseId = 9, Name = "SH-01" },
			new Group { GroupId = 9, CourseId = 5, Name = "SQ-06" },
			new Group { GroupId = 10, CourseId = 6, Name = "SW-95" },
			new Group { GroupId = 11, CourseId = 7, Name = "SJ-06" },
			new Group { GroupId = 12, CourseId = 8, Name = "GR-03" },
			new Group { GroupId = 13, CourseId = 6, Name = "VR-05" },
			new Group { GroupId = 14, CourseId = 7, Name = "HR-06" },
			new Group { GroupId = 15, CourseId = 2, Name = "MR-63" },
			new Group { GroupId = 16, CourseId = 6, Name = "LR-42" },
			new Group { GroupId = 17, CourseId = 8, Name = "AR-13" },
			new Group { GroupId = 18, CourseId = 5, Name = "ZR-25" },
			new Group { GroupId = 19, CourseId = 6, Name = "BR-46" },
			new Group { GroupId = 20, CourseId = 4, Name = "MR-35" },
			new Group { GroupId = 21, CourseId = 4, Name = "OG-14" },
			new Group { GroupId = 22, CourseId = 9, Name = "SD-23" },
			new Group { GroupId = 23, CourseId = 6, Name = "VB-11" },
			new Group { GroupId = 24, CourseId = 4, Name = "BS-11" },
			new Group { GroupId = 25, CourseId = 2, Name = "MD-06" },
			new Group { GroupId = 26, CourseId = 6, Name = "AS-09" },
			new Group { GroupId = 27, CourseId = 8, Name = "ZB-08" },
			new Group { GroupId = 28, CourseId = 6, Name = "JT-03" },
			new Group { GroupId = 29, CourseId = 7, Name = "SD-08" },
			new Group { GroupId = 30, CourseId = 9, Name = "DJ-13" }
			);

		int id = 0;
		modelBuilder.Entity<Student>().HasData(
			new Student { StudentId = 1, GroupId = 13, FirstName = "Emmy", LastName = "Scrammage"},
			new Student { StudentId = 2, GroupId = 19, FirstName = "Cherice", LastName = "Champkin"},
			new Student { StudentId = 3, GroupId = 14, FirstName = "Leonhard", LastName = "Petchey"},
			new Student { StudentId = 4, GroupId = 26, FirstName = "Margo", LastName = "Brister"},
			new Student { StudentId = 5, GroupId = 24, FirstName = "Kearney", LastName = "Sauvain"},
			new Student { StudentId = 6, GroupId = 15, FirstName = "Mora", LastName = "Spawforth"},
			new Student { StudentId = 7, GroupId = 11, FirstName = "Ernesto", LastName = "Prester"},
			new Student { StudentId = 8, GroupId = 1, FirstName = "Denise", LastName = "Mundow"},
			new Student { StudentId = 9, GroupId = 27, FirstName = "Cary", LastName = "Bohey"},
			new Student { StudentId = 10, GroupId = 7, FirstName = "Guido", LastName = "Overstreet"},
			new Student { StudentId = 11, GroupId = 30, FirstName = "Gusti", LastName = "Croisdall"},
			new Student { StudentId = 12, GroupId = 13, FirstName = "Samuele", LastName = "Pashenkov"},
			new Student { StudentId = 13, GroupId = 5, FirstName = "Esme", LastName = "Stoggles"},
			new Student { StudentId = 14, GroupId = 12, FirstName = "Nady", LastName = "Yegorkin"},
			new Student { StudentId = 15, GroupId = 27, FirstName = "Glenden", LastName = "Donnel"},
			new Student { StudentId = 16, GroupId = 3, FirstName = "Joey", LastName = "Potebury"},
			new Student { StudentId = 17, GroupId = 21, FirstName = "Silas", LastName = "Rowth"},
			new Student { StudentId = 18, GroupId = 19, FirstName = "Jaimie", LastName = "Vicioso"},
			new Student { StudentId = 19, GroupId = 3, FirstName = "Dougy", LastName = "Carnduff"},
			new Student { StudentId = 20, GroupId = 20, FirstName = "Von", LastName = "Lindermann"},
			new Student { StudentId = 21, GroupId = 25, FirstName = "Gaylor", LastName = "Softley"},
			new Student { StudentId = 22, GroupId = 18, FirstName = "Elisa", LastName = "Birdsey"},
			new Student { StudentId = 23, GroupId = 26, FirstName = "Laurella", LastName = "Andrzejak"},
			new Student { StudentId = 24, GroupId = 18, FirstName = "Barton", LastName = "Kopmann"},
			new Student { StudentId = 25, GroupId = 19, FirstName = "Serge", LastName = "Sidebottom"},
			new Student { StudentId = 26, GroupId = 8, FirstName = "Nessy", LastName = "Imeson"},
			new Student { StudentId = 27, GroupId = 7, FirstName = "Evvie", LastName = "Dziwisz"},
			new Student { StudentId = 28, GroupId = 21, FirstName = "Robbert", LastName = "Hinchon"},
			new Student { StudentId = 29, GroupId = 4, FirstName = "Jerome", LastName = "Tremathack"},
			new Student { StudentId = 30, GroupId = 4, FirstName = "Jamey", LastName = "Rouse"},
			new Student { StudentId = 31, GroupId = 19, FirstName = "Lina", LastName = "Storer"},
			new Student { StudentId = 32, GroupId = 12, FirstName = "Dasha", LastName = "Pimme"},
			new Student { StudentId = 33, GroupId = 19, FirstName = "Austin", LastName = "Manjot"},
			new Student { StudentId = 34, GroupId = 11, FirstName = "Lissy", LastName = "Skune"},
			new Student { StudentId = 35, GroupId = 11, FirstName = "Ciel", LastName = "Laidlow"},
			new Student { StudentId = 36, GroupId = 6, FirstName = "Phineas", LastName = "Wealthall"},
			new Student { StudentId = 37, GroupId = 8, FirstName = "Ferris", LastName = "Kenney"},
			new Student { StudentId = 38, GroupId = 2, FirstName = "Kerwinn", LastName = "Emblen"},
			new Student { StudentId = 39, GroupId = 10, FirstName = "Bili", LastName = "Sandcroft"},
			new Student { StudentId = 40, GroupId = 24, FirstName = "Reamonn", LastName = "Ganter"},
			new Student { StudentId = 41, GroupId = 19, FirstName = "Tadeo", LastName = "Bispham"},
			new Student { StudentId = 42, GroupId = 26, FirstName = "Karin", LastName = "Hoodlass"},
			new Student { StudentId = 43, GroupId = 11, FirstName = "Archy", LastName = "Wawer"},
			new Student { StudentId = 44, GroupId = 14, FirstName = "Melitta", LastName = "Dilston"},
			new Student { StudentId = 45, GroupId = 11, FirstName = "Averil", LastName = "Norton"},
			new Student { StudentId = 46, GroupId = 26, FirstName = "Robbie", LastName = "Mapowder"},
			new Student { StudentId = 47, GroupId = 2, FirstName = "Paulie", LastName = "Abbets"},
			new Student { StudentId = 48, GroupId = 25, FirstName = "Dallis", LastName = "Sneden"},
			new Student { StudentId = 49, GroupId = 15, FirstName = "Brittne", LastName = "Jarrel"},
			new Student { StudentId = 50, GroupId = 29, FirstName = "Hettie", LastName = "Tranfield"},
			new Student { StudentId = 51, GroupId = 20, FirstName = "Asher", LastName = "Tickle"},
			new Student { StudentId = 52, GroupId = 30, FirstName = "Pasquale", LastName = "Novello"},
			new Student { StudentId = 53, GroupId = 6, FirstName = "Hy", LastName = "Wrightson"},
			new Student { StudentId = 54, GroupId = 2, FirstName = "Pepillo", LastName = "Gernier"},
			new Student { StudentId = 55, GroupId = 21, FirstName = "Myca", LastName = "Strainge"},
			new Student { StudentId = 56, GroupId = 17, FirstName = "Aleece", LastName = "Allsup"},
			new Student { StudentId = 57, GroupId = 27, FirstName = "Vassili", LastName = "Goslin"},
			new Student { StudentId = 58, GroupId = 5, FirstName = "Dede", LastName = "Ambler"},
			new Student { StudentId = 59, GroupId = 17, FirstName = "Jessika", LastName = "Fawckner"},
			new Student { StudentId = 60, GroupId = 23, FirstName = "Eimile", LastName = "Perrott"},
			new Student { StudentId = 61, GroupId = 21, FirstName = "Lottie", LastName = "Cutriss"},
			new Student { StudentId = 62, GroupId = 9, FirstName = "Angelica", LastName = "Dalton"},
			new Student { StudentId = 63, GroupId = 22, FirstName = "Skip", LastName = "Sandcroft"},
			new Student { StudentId = 64, GroupId = 3, FirstName = "Davidson", LastName = "Chapleo"},
			new Student { StudentId = 65, GroupId = 10, FirstName = "Sheila", LastName = "Rosenbaum"},
			new Student { StudentId = 66, GroupId = 6, FirstName = "Cynde", LastName = "Boobier"},
			new Student { StudentId = 67, GroupId = 26, FirstName = "Bernadette", LastName = "Fothergill"},
			new Student { StudentId = 68, GroupId = 17, FirstName = "Bernardo", LastName = "Jansema"},
			new Student { StudentId = 69, GroupId = 27, FirstName = "Abbye", LastName = "McCrachen"},
			new Student { StudentId = 70, GroupId = 29, FirstName = "Reuven", LastName = "Ginner"},
			new Student { StudentId = 71, GroupId = 5, FirstName = "Kikelia", LastName = "Mertgen"},
			new Student { StudentId = 72, GroupId = 8, FirstName = "Tammie", LastName = "Iiannone"},
			new Student { StudentId = 73, GroupId = 5, FirstName = "Haley", LastName = "Giraldez"},
			new Student { StudentId = 74, GroupId = 25, FirstName = "Bill", LastName = "Ickowicz"},
			new Student { StudentId = 75, GroupId = 25, FirstName = "Storm", LastName = "Dodson"},
			new Student { StudentId = 76, GroupId = 20, FirstName = "Evy", LastName = "Hamnet"},
			new Student { StudentId = 77, GroupId = 20, FirstName = "Gerick", LastName = "Tracy"},
			new Student { StudentId = 78, GroupId = 16, FirstName = "Wayland", LastName = "Annon"},
			new Student { StudentId = 79, GroupId = 23, FirstName = "Penrod", LastName = "Iron"},
			new Student { StudentId = 80, GroupId = 5, FirstName = "Janet", LastName = "Delahunty"},
			new Student { StudentId = 81, GroupId = 9, FirstName = "Jarrad", LastName = "Sissons"},
			new Student { StudentId = 82, GroupId = 16, FirstName = "Maure", LastName = "Yurivtsev"},
			new Student { StudentId = 83, GroupId = 23, FirstName = "Giselle", LastName = "Camus"},
			new Student { StudentId = 84, GroupId = 13, FirstName = "Ivette", LastName = "Tissell"},
			new Student { StudentId = 85, GroupId = 27, FirstName = "Armando", LastName = "Savege"},
			new Student { StudentId = 86, GroupId = 28, FirstName = "Cameron", LastName = "Bandt"},
			new Student { StudentId = 87, GroupId = 13, FirstName = "Si", LastName = "Giller"},
			new Student { StudentId = 88, GroupId = 28, FirstName = "Corrine", LastName = "De Matteis"},
			new Student { StudentId = 89, GroupId = 11, FirstName = "Katheryn", LastName = "Gelder"},
			new Student { StudentId = 90, GroupId = 11, FirstName = "Hatty", LastName = "Knappe"},
			new Student { StudentId = 91, GroupId = 20, FirstName = "Nadya", LastName = "Vedishchev"},
			new Student { StudentId = 92, GroupId = 30, FirstName = "Carmencita", LastName = "Gaskin"},
			new Student { StudentId = 93, GroupId = 19, FirstName = "Leone", LastName = "Gullick"},
			new Student { StudentId = 94, GroupId = 19, FirstName = "Roseann", LastName = "Fanstone"},
			new Student { StudentId = 95, GroupId = 21, FirstName = "Tucker", LastName = "Tuison"},
			new Student { StudentId = 96, GroupId = 21, FirstName = "Cornie", LastName = "Kristoffersen"},
			new Student { StudentId = 97, GroupId = 20, FirstName = "Corty", LastName = "Hay"},
			new Student { StudentId = 98, GroupId = 24, FirstName = "Michail", LastName = "Hemerijk"},
			new Student { StudentId = 99, GroupId = 15, FirstName = "Luz", LastName = "Leynton"},
			new Student { StudentId = 100, GroupId = 2, FirstName = "Nanine", LastName = "Fulop"},
			new Student { StudentId = 101, GroupId = 2, FirstName = "Jerrine", LastName = "Dunnet"},
			new Student { StudentId = 102, GroupId = 29, FirstName = "Aleta", LastName = "Spurryer"},
			new Student { StudentId = 103, GroupId = 13, FirstName = "Kariotta", LastName = "Fratson"},
			new Student { StudentId = 104, GroupId = 3, FirstName = "Jason", LastName = "Francescoccio"},
			new Student { StudentId = 105, GroupId = 10, FirstName = "Bethena", LastName = "McInulty"},
			new Student { StudentId = 106, GroupId = 7, FirstName = "Lucia", LastName = "Bemlott"},
			new Student { StudentId = 107, GroupId = 24, FirstName = "Maryellen", LastName = "Belfit"},
			new Student { StudentId = 108, GroupId = 17, FirstName = "Janette", LastName = "Beetham"},
			new Student { StudentId = 109, GroupId = 3, FirstName = "Arley", LastName = "Barber"},
			new Student { StudentId = 110, GroupId = 14, FirstName = "Maxwell", LastName = "Elgee"},
			new Student { StudentId = 111, GroupId = 11, FirstName = "Denna", LastName = "Ind"},
			new Student { StudentId = 112, GroupId = 6, FirstName = "Slade", LastName = "Lording"},
			new Student { StudentId = 113, GroupId = 25, FirstName = "Lyndell", LastName = "Terzo"},
			new Student { StudentId = 114, GroupId = 4, FirstName = "Harold", LastName = "Trahair"},
			new Student { StudentId = 115, GroupId = 4, FirstName = "Karlik", LastName = "Nudd"},
			new Student { StudentId = 116, GroupId = 20, FirstName = "Ilaire", LastName = "Skoggings"},
			new Student { StudentId = 117, GroupId = 4, FirstName = "Phaidra", LastName = "Kroll"},
			new Student { StudentId = 118, GroupId = 19, FirstName = "Jarid", LastName = "Beckensall"},
			new Student { StudentId = 119, GroupId = 9, FirstName = "Hewett", LastName = "Grewcock"},
			new Student { StudentId = 120, GroupId = 18, FirstName = "Gipsy", LastName = "Reiach"},
			new Student { StudentId = 121, GroupId = 24, FirstName = "Isis", LastName = "Nelligan"},
			new Student { StudentId = 122, GroupId = 11, FirstName = "Burgess", LastName = "Petken"},
			new Student { StudentId = 123, GroupId = 25, FirstName = "Richard", LastName = "Emmens"},
			new Student { StudentId = 124, GroupId = 22, FirstName = "Lemar", LastName = "Bartrum"},
			new Student { StudentId = 125, GroupId = 15, FirstName = "Gui", LastName = "Lathee"},
			new Student { StudentId = 126, GroupId = 3, FirstName = "Elbertine", LastName = "Scuse"},
			new Student { StudentId = 127, GroupId = 26, FirstName = "Oliy", LastName = "Yukhtin"},
			new Student { StudentId = 128, GroupId = 24, FirstName = "Kaela", LastName = "Mollnar"},
			new Student { StudentId = 129, GroupId = 4, FirstName = "Neel", LastName = "Hynard"},
			new Student { StudentId = 130, GroupId = 21, FirstName = "Fransisco", LastName = "MacAskie"},
			new Student { StudentId = 131, GroupId = 7, FirstName = "Tibold", LastName = "Sorro"},
			new Student { StudentId = 132, GroupId = 4, FirstName = "Noell", LastName = "Kear"},
			new Student { StudentId = 133, GroupId = 6, FirstName = "Marlow", LastName = "Farriar"},
			new Student { StudentId = 134, GroupId = 28, FirstName = "Brigham", LastName = "Alvis"},
			new Student { StudentId = 135, GroupId = 5, FirstName = "Creigh", LastName = "McGilleghole"},
			new Student { StudentId = 136, GroupId = 25, FirstName = "Law", LastName = "Wearing"},
			new Student { StudentId = 137, GroupId = 19, FirstName = "Cora", LastName = "Whorall"},
			new Student { StudentId = 138, GroupId = 6, FirstName = "Humfrey", LastName = "Glanfield"},
			new Student { StudentId = 139, GroupId = 23, FirstName = "Sydney", LastName = "Abramin"},
			new Student { StudentId = 140, GroupId = 14, FirstName = "Cyril", LastName = "Hargreaves"},
			new Student { StudentId = 141, GroupId = 3, FirstName = "Wanids", LastName = "Brine"},
			new Student { StudentId = 142, GroupId = 11, FirstName = "Coralyn", LastName = "Jury"},
			new Student { StudentId = 143, GroupId = 20, FirstName = "Caralie", LastName = "Dunkersley"},
			new Student { StudentId = 144, GroupId = 7, FirstName = "Merill", LastName = "Gianni"},
			new Student { StudentId = 145, GroupId = 1, FirstName = "Adrianne", LastName = "Cholwell"},
			new Student { StudentId = 146, GroupId = 7, FirstName = "Hedwig", LastName = "Lattos"},
			new Student { StudentId = 147, GroupId = 8, FirstName = "Elna", LastName = "Tiley"},
			new Student { StudentId = 148, GroupId = 29, FirstName = "Bronnie", LastName = "Blainey"},
			new Student { StudentId = 149, GroupId = 1, FirstName = "Quent", LastName = "Crevan"},
			new Student { StudentId = 150, GroupId = 25, FirstName = "Blanca", LastName = "Olech"},
			new Student { StudentId = 151, GroupId = 22, FirstName = "Marmaduke", LastName = "Lambart"},
			new Student { StudentId = 152, GroupId = 3, FirstName = "Tamiko", LastName = "Archambault"},
			new Student { StudentId = 153, GroupId = 6, FirstName = "Egor", LastName = "Florez"},
			new Student { StudentId = 154, GroupId = 4, FirstName = "Aldwin", LastName = "Linch"},
			new Student { StudentId = 155, GroupId = 3, FirstName = "Keane", LastName = "Hazzard"},
			new Student { StudentId = 156, GroupId = 23, FirstName = "Allard", LastName = "McAuslene"},
			new Student { StudentId = 157, GroupId = 7, FirstName = "Veda", LastName = "Wastling"},
			new Student { StudentId = 158, GroupId = 23, FirstName = "Leona", LastName = "Petruk"},
			new Student { StudentId = 159, GroupId = 25, FirstName = "Margeaux", LastName = "Pressman"},
			new Student { StudentId = 160, GroupId = 22, FirstName = "Giorgio", LastName = "Shaul"},
			new Student { StudentId = 161, GroupId = 25, FirstName = "Reinaldo", LastName = "Ceschini"},
			new Student { StudentId = 162, GroupId = 24, FirstName = "Deidre", LastName = "Folli"},
			new Student { StudentId = 163, GroupId = 3, FirstName = "Wait", LastName = "Domesday"},
			new Student { StudentId = 164, GroupId = 2, FirstName = "Cami", LastName = "Luparti"},
			new Student { StudentId = 165, GroupId = 16, FirstName = "Maria", LastName = "Gerardet"},
			new Student { StudentId = 166, GroupId = 23, FirstName = "Berni", LastName = "Antonich"},
			new Student { StudentId = 167, GroupId = 30, FirstName = "Happy", LastName = "Leagas"},
			new Student { StudentId = 168, GroupId = 9, FirstName = "Stacee", LastName = "Mounfield"},
			new Student { StudentId = 169, GroupId = 15, FirstName = "Kennan", LastName = "Flowerden"},
			new Student { StudentId = 170, GroupId = 20, FirstName = "Elva", LastName = "Vicarey"},
			new Student { StudentId = 171, GroupId = 22, FirstName = "Karlene", LastName = "Jolland"},
			new Student { StudentId = 172, GroupId = 13, FirstName = "Goran", LastName = "McKeller"},
			new Student { StudentId = 173, GroupId = 30, FirstName = "Reinhard", LastName = "Sheavills"},
			new Student { StudentId = 174, GroupId = 3, FirstName = "Dorelle", LastName = "Baber"},
			new Student { StudentId = 175, GroupId = 5, FirstName = "Vi", LastName = "Leed"},
			new Student { StudentId = 176, GroupId = 22, FirstName = "Tracey", LastName = "Eingerfield"},
			new Student { StudentId = 177, GroupId = 6, FirstName = "Cory", LastName = "Cutill"},
			new Student { StudentId = 178, GroupId = 28, FirstName = "Nevil", LastName = "Hearnshaw"},
			new Student { StudentId = 179, GroupId = 28, FirstName = "Ortensia", LastName = "Leese"},
			new Student { StudentId = 180, GroupId = 8, FirstName = "Mildred", LastName = "Currer"},
			new Student { StudentId = 181, GroupId = 23, FirstName = "Ephrayim", LastName = "Korfmann"},
			new Student { StudentId = 182, GroupId = 25, FirstName = "Berky", LastName = "Tapply"},
			new Student { StudentId = 183, GroupId = 30, FirstName = "Cyndia", LastName = "Wrankling"},
			new Student { StudentId = 184, GroupId = 17, FirstName = "Tammy", LastName = "Bleasdille"},
			new Student { StudentId = 185, GroupId = 1, FirstName = "Esra", LastName = "Brient"},
			new Student { StudentId = 186, GroupId = 2, FirstName = "Elena", LastName = "Sargant"},
			new Student { StudentId = 187, GroupId = 8, FirstName = "Flem", LastName = "McSherry"},
			new Student { StudentId = 188, GroupId = 30, FirstName = "Merrick", LastName = "Gideon"},
			new Student { StudentId = 189, GroupId = 25, FirstName = "Monti", LastName = "Scollee"},
			new Student { StudentId = 190, GroupId = 4, FirstName = "Jarrett", LastName = "Froud"},
			new Student { StudentId = 191, GroupId = 29, FirstName = "Violette", LastName = "Durden"},
			new Student { StudentId = 192, GroupId = 26, FirstName = "Morlee", LastName = "Kellog"},
			new Student { StudentId = 193, GroupId = 19, FirstName = "Rutger", LastName = "Spurgeon"},
			new Student { StudentId = 194, GroupId = 5, FirstName = "Kakalina", LastName = "Vashchenko"},
			new Student { StudentId = 195, GroupId = 20, FirstName = "Jeni", LastName = "Peaker"},
			new Student { StudentId = 196, GroupId = 17, FirstName = "Tannie", LastName = "Gabriel"},
			new Student { StudentId = 197, GroupId = 27, FirstName = "Brewer", LastName = "Bartholomew"},
			new Student { StudentId = 198, GroupId = 22, FirstName = "Martie", LastName = "Strand"},
			new Student { StudentId = 199, GroupId = 27, FirstName = "Arlana", LastName = "Paulin"},
			new Student { StudentId = 200, GroupId = 1, FirstName = "Kameko", LastName = "Dayne"},
			new Student { StudentId = 201, GroupId = 25, FirstName = "Vaughn", LastName = "Finci"},
			new Student { StudentId = 202, GroupId = 3, FirstName = "Maitilde", LastName = "Torrese"},
			new Student { StudentId = 203, GroupId = 7, FirstName = "Renata", LastName = "Kopelman"},
			new Student { StudentId = 204, GroupId = 6, FirstName = "Irvine", LastName = "Schoolfield"},
			new Student { StudentId = 205, GroupId = 25, FirstName = "Zechariah", LastName = "Headly"},
			new Student { StudentId = 206, GroupId = 14, FirstName = "Bart", LastName = "Taaffe"},
			new Student { StudentId = 207, GroupId = 24, FirstName = "Tallie", LastName = "Hargraves"},
			new Student { StudentId = 208, GroupId = 6, FirstName = "Venita", LastName = "Liebrecht"},
			new Student { StudentId = 209, GroupId = 19, FirstName = "Cordey", LastName = "Kerbler"},
			new Student { StudentId = 210, GroupId = 2, FirstName = "Staci", LastName = "Pellissier"},
			new Student { StudentId = 211, GroupId = 4, FirstName = "Tybie", LastName = "Stonard"},
			new Student { StudentId = 212, GroupId = 4, FirstName = "Cozmo", LastName = "Lugton"},
			new Student { StudentId = 213, GroupId = 14, FirstName = "Cynthy", LastName = "Crosseland"},
			new Student { StudentId = 214, GroupId = 27, FirstName = "Clifford", LastName = "Kildea"},
			new Student { StudentId = 215, GroupId = 28, FirstName = "Garrard", LastName = "Mum"},
			new Student { StudentId = 216, GroupId = 10, FirstName = "Lynn", LastName = "Cockshoot"},
			new Student { StudentId = 217, GroupId = 28, FirstName = "Kerwin", LastName = "Mullins"},
			new Student { StudentId = 218, GroupId = 23, FirstName = "Corrinne", LastName = "Dominicacci"},
			new Student { StudentId = 219, GroupId = 1, FirstName = "Georgie", LastName = "Bamforth"},
			new Student { StudentId = 220, GroupId = 3, FirstName = "Emmery", LastName = "Miell"},
			new Student { StudentId = 221, GroupId = 8, FirstName = "Pincas", LastName = "Sailer"},
			new Student { StudentId = 222, GroupId = 10, FirstName = "Elyssa", LastName = "Craghead"},
			new Student { StudentId = 223, GroupId = 25, FirstName = "Melissa", LastName = "Mallam"},
			new Student { StudentId = 224, GroupId = 23, FirstName = "Pippo", LastName = "Claxson"},
			new Student { StudentId = 225, GroupId = 3, FirstName = "Dyanne", LastName = "Hambelton"},
			new Student { StudentId = 226, GroupId = 9, FirstName = "Sebastiano", LastName = "Krugmann"},
			new Student { StudentId = 227, GroupId = 2, FirstName = "Nadiya", LastName = "Bofield"},
			new Student { StudentId = 228, GroupId = 3, FirstName = "Herculie", LastName = "Edmonston"},
			new Student { StudentId = 229, GroupId = 27, FirstName = "Ronnie", LastName = "Janos"},
			new Student { StudentId = 230, GroupId = 16, FirstName = "Lothario", LastName = "Kiddie"},
			new Student { StudentId = 231, GroupId = 8, FirstName = "Arlinda", LastName = "Richford"},
			new Student { StudentId = 232, GroupId = 24, FirstName = "Brig", LastName = "Skiggs"},
			new Student { StudentId = 233, GroupId = 17, FirstName = "Almire", LastName = "Crother"},
			new Student { StudentId = 234, GroupId = 20, FirstName = "Mathias", LastName = "Prestland"},
			new Student { StudentId = 235, GroupId = 27, FirstName = "Fredia", LastName = "Duck"},
			new Student { StudentId = 236, GroupId = 13, FirstName = "Ameline", LastName = "Labrone"},
			new Student { StudentId = 237, GroupId = 10, FirstName = "Shannan", LastName = "Methringham"},
			new Student { StudentId = 238, GroupId = 4, FirstName = "Giacomo", LastName = "Chafney"},
			new Student { StudentId = 239, GroupId = 4, FirstName = "Bucky", LastName = "Halson"},
			new Student { StudentId = 240, GroupId = 1, FirstName = "Heriberto", LastName = "Krink"},
			new Student { StudentId = 241, GroupId = 22, FirstName = "Raimundo", LastName = "Oxtarby"},
			new Student { StudentId = 242, GroupId = 16, FirstName = "Chelsie", LastName = "Sappell"},
			new Student { StudentId = 243, GroupId = 25, FirstName = "Wash", LastName = "Orriss"},
			new Student { StudentId = 244, GroupId = 3, FirstName = "April", LastName = "Kinnerley"},
			new Student { StudentId = 245, GroupId = 20, FirstName = "Kissiah", LastName = "Pither"},
			new Student { StudentId = 246, GroupId = 21, FirstName = "Astra", LastName = "Oxterby"},
			new Student { StudentId = 247, GroupId = 23, FirstName = "Bill", LastName = "Knowlys"},
			new Student { StudentId = 248, GroupId = 30, FirstName = "Balduin", LastName = "Fidal"},
			new Student { StudentId = 249, GroupId = 10, FirstName = "Shepard", LastName = "Settle"},
			new Student { StudentId = 250, GroupId = 11, FirstName = "Arlena", LastName = "Guerola"},
			new Student { StudentId = 251, GroupId = 27, FirstName = "Cherry", LastName = "Kilmaster"},
			new Student { StudentId = 252, GroupId = 9, FirstName = "Paige", LastName = "Mityashin"},
			new Student { StudentId = 253, GroupId = 29, FirstName = "Graehme", LastName = "Heskin"},
			new Student { StudentId = 254, GroupId = 19, FirstName = "Tess", LastName = "Mariaud"},
			new Student { StudentId = 255, GroupId = 3, FirstName = "Loydie", LastName = "Bruntjen"},
			new Student { StudentId = 256, GroupId = 5, FirstName = "Mattie", LastName = "Abbots"},
			new Student { StudentId = 257, GroupId = 8, FirstName = "Bary", LastName = "Laxtonne"},
			new Student { StudentId = 258, GroupId = 13, FirstName = "Sheri", LastName = "Schanke"},
			new Student { StudentId = 259, GroupId = 28, FirstName = "Enid", LastName = "Smoughton"},
			new Student { StudentId = 260, GroupId = 7, FirstName = "Radcliffe", LastName = "Geare"},
			new Student { StudentId = 261, GroupId = 30, FirstName = "Adrianne", LastName = "Rennock"},
			new Student { StudentId = 262, GroupId = 14, FirstName = "Basile", LastName = "Portman"},
			new Student { StudentId = 263, GroupId = 5, FirstName = "Vittorio", LastName = "Hadigate"},
			new Student { StudentId = 264, GroupId = 6, FirstName = "Honor", LastName = "Isakovitch"},
			new Student { StudentId = 265, GroupId = 1, FirstName = "Bil", LastName = "Heather"},
			new Student { StudentId = 266, GroupId = 29, FirstName = "Al", LastName = "Huriche"},
			new Student { StudentId = 267, GroupId = 20, FirstName = "Sly", LastName = "Race"},
			new Student { StudentId = 268, GroupId = 26, FirstName = "Alis", LastName = "Joyes"},
			new Student { StudentId = 269, GroupId = 8, FirstName = "Cleopatra", LastName = "Mathissen"},
			new Student { StudentId = 270, GroupId = 2, FirstName = "Cyrus", LastName = "Tow"},
			new Student { StudentId = 271, GroupId = 8, FirstName = "Yancey", LastName = "Barthrup"},
			new Student { StudentId = 272, GroupId = 12, FirstName = "Bendite", LastName = "Schulze"},
			new Student { StudentId = 273, GroupId = 3, FirstName = "Minette", LastName = "Ferrao"},
			new Student { StudentId = 274, GroupId = 4, FirstName = "Peder", LastName = "Michie"},
			new Student { StudentId = 275, GroupId = 17, FirstName = "Gianni", LastName = "Crathorne"},
			new Student { StudentId = 276, GroupId = 28, FirstName = "Donny", LastName = "Disney"},
			new Student { StudentId = 277, GroupId = 21, FirstName = "Letty", LastName = "Whates"},
			new Student { StudentId = 278, GroupId = 27, FirstName = "Noami", LastName = "Coole"},
			new Student { StudentId = 279, GroupId = 28, FirstName = "Sarene", LastName = "Jori"},
			new Student { StudentId = 280, GroupId = 5, FirstName = "Putnem", LastName = "Bodycomb"},
			new Student { StudentId = 281, GroupId = 5, FirstName = "Emmery", LastName = "Kubu"},
			new Student { StudentId = 282, GroupId = 27, FirstName = "Dulcie", LastName = "Girardin"},
			new Student { StudentId = 283, GroupId = 5, FirstName = "Nels", LastName = "Suggate"},
			new Student { StudentId = 284, GroupId = 23, FirstName = "Stacey", LastName = "Truesdale"},
			new Student { StudentId = 285, GroupId = 14, FirstName = "Danyette", LastName = "Chattoe"},
			new Student { StudentId = 286, GroupId = 1, FirstName = "Lynett", LastName = "Tamblingson"},
			new Student { StudentId = 287, GroupId = 2, FirstName = "Hamlin", LastName = "Morffew"},
			new Student { StudentId = 288, GroupId = 13, FirstName = "Hamish", LastName = "Chamberlen"},
			new Student { StudentId = 289, GroupId = 16, FirstName = "Abbott", LastName = "Darrel"},
			new Student { StudentId = 290, GroupId = 14, FirstName = "Willi", LastName = "Tinan"},
			new Student { StudentId = 291, GroupId = 9, FirstName = "Jill", LastName = "Horick"},
			new Student { StudentId = 292, GroupId = 21, FirstName = "Lara", LastName = "Matzl"},
			new Student { StudentId = 293, GroupId = 21, FirstName = "Asher", LastName = "Keppel"},
			new Student { StudentId = 294, GroupId = 16, FirstName = "Tiebout", LastName = "Gandrich"},
			new Student { StudentId = 295, GroupId = 17, FirstName = "Minette", LastName = "Wims"},
			new Student { StudentId = 296, GroupId = 13, FirstName = "Sheelagh", LastName = "Greim"},
			new Student { StudentId = 297, GroupId = 11, FirstName = "Hamilton", LastName = "Lippingwell"},
			new Student { StudentId = 298, GroupId = 29, FirstName = "Will", LastName = "Akrigg"},
			new Student { StudentId = 299, GroupId = 4, FirstName = "Bendite", LastName = "Sadat"},
			new Student { StudentId = 300, GroupId = 7, FirstName = "Suzie", LastName = "Hallam"},
			new Student { StudentId = 301, GroupId = 24, FirstName = "Gustaf", LastName = "Pammenter"},
			new Student { StudentId = 302, GroupId = 22, FirstName = "Allsun", LastName = "Mantz"},
			new Student { StudentId = 303, GroupId = 3, FirstName = "Garth", LastName = "Powrie"},
			new Student { StudentId = 304, GroupId = 9, FirstName = "Joey", LastName = "Couthard"},
			new Student { StudentId = 305, GroupId = 12, FirstName = "Sileas", LastName = "Egarr"},
			new Student { StudentId = 306, GroupId = 30, FirstName = "Timmie", LastName = "Dantesia"},
			new Student { StudentId = 307, GroupId = 20, FirstName = "Cathryn", LastName = "Trivett"},
			new Student { StudentId = 308, GroupId = 29, FirstName = "Hamnet", LastName = "Alger"},
			new Student { StudentId = 309, GroupId = 29, FirstName = "Vaclav", LastName = "Wilcocke"},
			new Student { StudentId = 310, GroupId = 12, FirstName = "Inigo", LastName = "Pascoe"},
			new Student { StudentId = 311, GroupId = 22, FirstName = "Wendall", LastName = "Over"},
			new Student { StudentId = 312, GroupId = 5, FirstName = "Myra", LastName = "Tidbold"},
			new Student { StudentId = 313, GroupId = 6, FirstName = "Ave", LastName = "Nollet"},
			new Student { StudentId = 314, GroupId = 1, FirstName = "Paule", LastName = "Senior"},
			new Student { StudentId = 315, GroupId = 7, FirstName = "Tabbitha", LastName = "Filippozzi"},
			new Student { StudentId = 316, GroupId = 20, FirstName = "Kathye", LastName = "Strewther"},
			new Student { StudentId = 317, GroupId = 5, FirstName = "Falito", LastName = "Grimley"},
			new Student { StudentId = 318, GroupId = 27, FirstName = "Camellia", LastName = "Derry"},
			new Student { StudentId = 319, GroupId = 7, FirstName = "Jenni", LastName = "Buffey"},
			new Student { StudentId = 320, GroupId = 9, FirstName = "Shandeigh", LastName = "Bignall"},
			new Student { StudentId = 321, GroupId = 6, FirstName = "Jedd", LastName = "MacVicar"},
			new Student { StudentId = 322, GroupId = 18, FirstName = "Editha", LastName = "Perche"},
			new Student { StudentId = 323, GroupId = 14, FirstName = "Felicdad", LastName = "Foker"},
			new Student { StudentId = 324, GroupId = 12, FirstName = "Grace", LastName = "Looby"},
			new Student { StudentId = 325, GroupId = 9, FirstName = "Melisse", LastName = "Inglesent"},
			new Student { StudentId = 326, GroupId = 18, FirstName = "Valeda", LastName = "McJerrow"},
			new Student { StudentId = 327, GroupId = 1, FirstName = "Vick", LastName = "Craise"},
			new Student { StudentId = 328, GroupId = 1, FirstName = "Kori", LastName = "Ferrettini"},
			new Student { StudentId = 329, GroupId = 17, FirstName = "Madelle", LastName = "Barensky"},
			new Student { StudentId = 330, GroupId = 14, FirstName = "Christina", LastName = "Janaszewski"},
			new Student { StudentId = 331, GroupId = 4, FirstName = "Konstanze", LastName = "Bradneck"},
			new Student { StudentId = 332, GroupId = 16, FirstName = "Franny", LastName = "Stell"},
			new Student { StudentId = 333, GroupId = 3, FirstName = "Raphaela", LastName = "Klemke"},
			new Student { StudentId = 334, GroupId = 11, FirstName = "Bartie", LastName = "Creggan"},
			new Student { StudentId = 335, GroupId = 30, FirstName = "Leo", LastName = "Lunney"},
			new Student { StudentId = 336, GroupId = 6, FirstName = "Abbe", LastName = "Farge"},
			new Student { StudentId = 337, GroupId = 6, FirstName = "Ralina", LastName = "Harfoot"},
			new Student { StudentId = 338, GroupId = 16, FirstName = "Kristine", LastName = "Longain"},
			new Student { StudentId = 339, GroupId = 5, FirstName = "Yalonda", LastName = "Ratlee"},
			new Student { StudentId = 340, GroupId = 15, FirstName = "Mable", LastName = "Kullmann"},
			new Student { StudentId = 341, GroupId = 5, FirstName = "Tye", LastName = "Cheson"},
			new Student { StudentId = 342, GroupId = 25, FirstName = "Rickie", LastName = "Dallyn"},
			new Student { StudentId = 343, GroupId = 6, FirstName = "Averyl", LastName = "Rook"},
			new Student { StudentId = 344, GroupId = 14, FirstName = "Ferdinand", LastName = "Jerrand"},
			new Student { StudentId = 345, GroupId = 19, FirstName = "Donovan", LastName = "Jensen"},
			new Student { StudentId = 346, GroupId = 19, FirstName = "Wash", LastName = "Edgeley"},
			new Student { StudentId = 347, GroupId = 30, FirstName = "Mamie", LastName = "Nezey"},
			new Student { StudentId = 348, GroupId = 12, FirstName = "Brigitte", LastName = "Midghall"},
			new Student { StudentId = 349, GroupId = 24, FirstName = "Ruthie", LastName = "Baildon"},
			new Student { StudentId = 350, GroupId = 2, FirstName = "Paton", LastName = "Tims"},
			new Student { StudentId = 351, GroupId = 21, FirstName = "Elia", LastName = "Itzkovwitch"},
			new Student { StudentId = 352, GroupId = 24, FirstName = "Rhiamon", LastName = "Rotte"},
			new Student { StudentId = 353, GroupId = 25, FirstName = "Flint", LastName = "Cardoo"},
			new Student { StudentId = 354, GroupId = 9, FirstName = "Reginauld", LastName = "Cheesworth"},
			new Student { StudentId = 355, GroupId = 6, FirstName = "Mead", LastName = "Jones"},
			new Student { StudentId = 356, GroupId = 6, FirstName = "Clark", LastName = "Ambroise"},
			new Student { StudentId = 357, GroupId = 10, FirstName = "Finley", LastName = "Yoseloff"},
			new Student { StudentId = 358, GroupId = 10, FirstName = "Benson", LastName = "Claricoats"},
			new Student { StudentId = 359, GroupId = 9, FirstName = "Correna", LastName = "Roon"},
			new Student { StudentId = 360, GroupId = 5, FirstName = "Ellis", LastName = "Lindhe"},
			new Student { StudentId = 361, GroupId = 19, FirstName = "Juliana", LastName = "Maryott"},
			new Student { StudentId = 362, GroupId = 19, FirstName = "Leopold", LastName = "Hassell"},
			new Student { StudentId = 363, GroupId = 18, FirstName = "Philippe", LastName = "Skully"},
			new Student { StudentId = 364, GroupId = 8, FirstName = "Merell", LastName = "Vidgeon"},
			new Student { StudentId = 365, GroupId = 25, FirstName = "Vitoria", LastName = "Antonikov"},
			new Student { StudentId = 366, GroupId = 27, FirstName = "Gwyneth", LastName = "Fane"},
			new Student { StudentId = 367, GroupId = 16, FirstName = "Lainey", LastName = "Itzkovwitch"},
			new Student { StudentId = 368, GroupId = 3, FirstName = "Thorstein", LastName = "Agar"},
			new Student { StudentId = 369, GroupId = 7, FirstName = "Selma", LastName = "Rafter"},
			new Student { StudentId = 370, GroupId = 11, FirstName = "Cecil", LastName = "Planke"},
			new Student { StudentId = 371, GroupId = 6, FirstName = "Tressa", LastName = "De Paepe"},
			new Student { StudentId = 372, GroupId = 23, FirstName = "Ruthi", LastName = "Pawling"},
			new Student { StudentId = 373, GroupId = 1, FirstName = "Bradford", LastName = "Renn"},
			new Student { StudentId = 374, GroupId = 29, FirstName = "Town", LastName = "Fass"},
			new Student { StudentId = 375, GroupId = 21, FirstName = "Ardisj", LastName = "Habbon"},
			new Student { StudentId = 376, GroupId = 28, FirstName = "Frederigo", LastName = "Parbrook"},
			new Student { StudentId = 377, GroupId = 15, FirstName = "Emyle", LastName = "Oloshkin"},
			new Student { StudentId = 378, GroupId = 9, FirstName = "Emile", LastName = "Rosini"},
			new Student { StudentId = 379, GroupId = 16, FirstName = "Harald", LastName = "McAneny"},
			new Student { StudentId = 380, GroupId = 8, FirstName = "Deeann", LastName = "Easter"},
			new Student { StudentId = 381, GroupId = 29, FirstName = "Yasmin", LastName = "Felton"},
			new Student { StudentId = 382, GroupId = 26, FirstName = "Suzi", LastName = "Bart"},
			new Student { StudentId = 383, GroupId = 14, FirstName = "Ashleigh", LastName = "McCandless"},
			new Student { StudentId = 384, GroupId = 20, FirstName = "Genni", LastName = "Bealing"},
			new Student { StudentId = 385, GroupId = 15, FirstName = "Kalie", LastName = "Crowcroft"},
			new Student { StudentId = 386, GroupId = 20, FirstName = "Rutter", LastName = "Karlqvist"},
			new Student { StudentId = 387, GroupId = 27, FirstName = "Cinda", LastName = "Twyning"},
			new Student { StudentId = 388, GroupId = 19, FirstName = "Abram", LastName = "Wickmann"},
			new Student { StudentId = 389, GroupId = 16, FirstName = "Kessiah", LastName = "Matresse"},
			new Student { StudentId = 390, GroupId = 24, FirstName = "Bartlett", LastName = "Beveridge"},
			new Student { StudentId = 391, GroupId = 12, FirstName = "Aimil", LastName = "Dudenie"},
			new Student { StudentId = 392, GroupId = 7, FirstName = "Brittani", LastName = "Wyldbore"},
			new Student { StudentId = 393, GroupId = 1, FirstName = "Aleksandr", LastName = "Staggs"},
			new Student { StudentId = 394, GroupId = 9, FirstName = "Whit", LastName = "Skedge"},
			new Student { StudentId = 395, GroupId = 9, FirstName = "Inez", LastName = "Bees"},
			new Student { StudentId = 396, GroupId = 17, FirstName = "Irwin", LastName = "Perillo"},
			new Student { StudentId = 397, GroupId = 12, FirstName = "Gardie", LastName = "Kopec"},
			new Student { StudentId = 398, GroupId = 16, FirstName = "Greg", LastName = "Dunkerly"},
			new Student { StudentId = 399, GroupId = 28, FirstName = "Dwayne", LastName = "Sangra"},
			new Student { StudentId = 400, GroupId = 9, FirstName = "Evangelina", LastName = "Morrid"}
			);
	}
}
